#!/usr/bin/env bash
# Installs nginx web server and configurations

sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
