#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/.*listen\s\+80.*/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo killall -s HUP nginx

# Create a simple index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
