#!/usr/bin/env bash

# Install nginx web server and configurations
sudo apt update
sudo apt install -y nginx

# Create the redirect configuration file
sudo echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        root /var/www/html;
        index index.html index.htm;

        # Add support for PHP scripts
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }
}" | sudo tee /etc/nginx/sites-available/redirect > /dev/null

# Enable the configuration file by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default symbolic link
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart

